/**
 * This is my work based on Git, which is an input method for the Traditional
 * Mongolian script. If the program has any errors, please understand that and
 * contact me. I will change the errors in a few days.
 */

( function ( $ ) {
	'use strict';

	var todoMongolian = {
		id: 'mo-mt',
		name: 'Mongolian Todo Scripts',
		description: 'Mongolian Todo Scripts',
		date: '2013-4-28',
		URL: 'http://github.com/wikimedia/jquery.ime',
		author: 'Feilong Huang, <huangfeilong@gmail.com>',
		license: 'GPLv3',
		version: '1.0',
		patterns: [
			['Q', '᠀'],
			['W', 'ᡖ'],
			['E', 'ᡃ'],
			['R', ''],
			['T', ''],
			['Y', ''],
			['U', ''],
			['I', ''],
			['O', ''],
			['P', ''],
			['{', '〈'],
			['}', '〉'],
			['A', '᠆'],
			['S', ''],
			['D', '᠅'],
			['F', ''],
			['G', 'ᡘ'],
			['H', 'ᡙ'],
			['J', 'ᠴ'],
			['K', ''],
			['L', 'ᡀ'],
			[':', '᠄'],
			['"', '᠌'],
			['Z', 'ᡚ'],
			['X', ''],
			['C', 'ᡔ'],
			['V', ''],
			['B', ''],
			['N', 'ᡊ'],
			['M', 'ᡛ'],
			['<', '《'],
			['>', '》'],
			['\\?', '?'],
			['_', '᠎'],
			['\\+', '+'],

			['q', 'ᡍ'],
			['w', 'ᡆ'],
			['e', 'ᡄ'],
			['r', 'ᠷ'],
			['t', 'ᡐ'],
			['y', 'ᡕ'],
			['u', 'ᡉ'],
			['i', 'ᡅ'],
			['o', 'ᡈ'],
			['p', 'ᡌ'],
			['\\[', '〔'],
			['\\]', '〕'],
			['a', 'ᠠ'],
			['s', 'ᠰ'],
			['d', 'ᡑ'],
			['f', 'ᠸ'],
			['g', 'ᡎ'],
			['h', 'ᡍ'],
			['j', 'ᡓ'],
			['k', 'ᡗ'],
			['l', 'ᠯ'],
			[';', ';'],
			['\'', '᠋'],
			['z', 'ᡜ'],
			['x', 'ᠱ'],
			['c', 'ᡒ'],
			['v', 'ᡇ'],
			['b', 'ᡋ'],
			['n', 'ᠨ'],
			['m', 'ᡏ'],
			[',', '᠂'],
			['\\.', '᠃'],
			['/', '.'],
			['\\-', ' '],
			['=', '='],

			['`', '᠍'],
			['~', '~'],
			['1', '1'],
			['2', '2'],
			['3', '3'],
			['4', '4'],
			['5', '5'],
			['6', '6'],
			['7', '7'],
			['8', '8'],
			['9', '9'],
			['0', '0'],
			['!', '!'],
			['@', '⁈'],
			['#', '⁉'],
			['\\$', '—'],
			['%', '%'],
			['^', '‌'],
			['&', '᠊'],
			['*', '‍'],
			['\\(', '('],
			['\\)', ')']
		]
	};

	$.ime.register( todoMongolian );

}( jQuery ) );
