/**
 * This is my work based on Git, which is an input method for the Traditional
 * Mongolian script. If the program has any errors, please understand that and
 * contact me. I will change the errors in a few days.
 */

( function ( $ ) {
	'use strict';

	var mongolian = {
		id: 'mn-tm',
		name: 'Traditional Mongolian Scripts',
		description: 'Traditional Mongolian Scripts',
		date: '2013-4-28',
		URL: 'http://github.com/wikimedia/jquery.ime',
		author: 'Feilong Huang, <huangfeilong@gmail.com>',
		license: 'GPLv3',
		version: '1.0',
		patterns: [
			['Q', ''],
			['W', 'ᠸ'],
			['E', 'ᠧ'],
			['R', 'ᠿ'],
			['T', ''],
			['Y', ''],
			['U', ''],
			['I', ''],
			['O', ''],
			['P', ''],
			['{', '〈'],
			['}', '〉'],
			['A', ''],
			['S', ''],
			['D', ''],
			['F', ''],
			['G', ''],
			['H', 'ᠾ'],
			['J', ''],
			['K', 'ᠻ'],
			['L', 'ᡀ'],
			[':', '᠄'],
			['"', '᠌'],
			['Z', 'ᡁ'],
			['X', ''],
			['C', 'ᡂ'],
			['V', ''],
			['B', ''],
			['N', 'ᠩ'],
			['M', ''],
			['<', '《'],
			['>', '》'],
			['\\?', '?'],
			['_', '᠎'],
			['\\+', '+'],

			['q', 'ᠴ'],
			['w', 'ᠣ'],
			['e', 'ᠡ'],
			['r', 'ᠷ'],
			['t', 'ᠲ'],
			['y', 'ᠶ'],
			['u', 'ᠦ'],
			['i', 'ᠢ'],
			['o', 'ᠥ'],
			['p', 'ᠫ'],
			['\\[', '〔'],
			['\\]', '〕'],
			['a', 'ᠠ'],
			['s', 'ᠰ'],
			['d', 'ᠳ'],
			['f', 'ᠹ'],
			['g', 'ᠭ'],
			['h', 'ᠬ'],
			['j', 'ᠵ'],
			['k', 'ᠺ'],
			['l', 'ᠯ'],
			[';', ';'],
			['\'', '᠋'],
			['z', 'ᠽ'],
			['x', 'ᠱ'],
			['c', 'ᠼ'],
			['v', 'ᠤ'],
			['b', 'ᠪ'],
			['n', 'ᠨ'],
			['m', 'ᠮ'],
			[',', '᠂'],
			['\\.', '᠃'],
			['/', '.'],
			['\\-', ' '],
			['=', '='],

			['`', '᠍'],
			['~', '~'],
			['1', '1'],
			['2', '2'],
			['3', '3'],
			['4', '4'],
			['5', '5'],
			['6', '6'],
			['7', '7'],
			['8', '8'],
			['9', '9'],
			['0', '0'],
			['!', '!'],
			['@', '⁈'],
			['#', '⁉'],
			['\\$', '—'],
			['%', '%'],
			['^', '‌'],
			['&', '᠊'],
			['*', '‍'],
			['\\(', '('],
			['\\)', ')']
		]
	};

	$.ime.register( mongolian );

}( jQuery ) );
